### ISSUE TITLE
warning: refname 'tags/website-complete-example' is ambiguous.

### ISSUE THREAD

**Issue by Yang-Rongquan** [hashicorp/learn-terraform-modules#4]
When runing `git checkout tags/website-complete-example -b website-complete-example`

There is a error
> warning: refname 'tags/website-complete-example' is ambiguous.
> warning: refname 'tags/website-complete-example' is ambiguous.
> fatal: Ambiguous object name: 'tags/website-complete-example'.

**Comment by hoodbu** [comment]
I am encountering this as well.

**Comment by MWatter** [comment]
This is due to there being two tags that are colliding:
```
tags/website-complete-example
website-complete-example
```

Until this is fixed in the remote repository, you can address it locally by removing one of the tags:
`git update-ref -d refs/tags/tags/website-complete-example`

At which point the original command in the tutorial will once again work:
`git checkout tags/website-complete-example -b website-complete-example`

**Comment by robin-norwood** [comment]
@Yang-Rongquan Thanks for reporting this! I've fixed the tag, and the instructions should work fine now.
